### ISSUE TITLE
use useEffect

### ISSUE THREAD

**Issue by alirrah** [alirrah/Authentication#7]
- in login page in username and password save and correct navigate to dashboard

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by alirrah** [comment]
> Can I get assigned? let me know how to start.

I saw your message late and did it myself
Thankful

**Comment by alirrah** [comment]
> Can I get assigned? let me know how to start.

I saw your message late and did it myself
Thankful
